// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBquyYHph6aBou3Iv5Mz5wbj13NtKZ-2ZU',
    appId: '1:1011408186:web:b80ba4b65de9c6247b8403',
    messagingSenderId: '1011408186',
    projectId: 'detection-app-23e70',
    authDomain: 'detection-app-23e70.firebaseapp.com',
    storageBucket: 'detection-app-23e70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJmVU5rUymC-4-XN0xHYJjE1X6CuSYzF0',
    appId: '1:1011408186:ios:3c928f0b7f2d4e1e7b8403',
    messagingSenderId: '1011408186',
    projectId: 'detection-app-23e70',
    storageBucket: 'detection-app-23e70.appspot.com',
    iosBundleId: 'com.example.detectionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJmVU5rUymC-4-XN0xHYJjE1X6CuSYzF0',
    appId: '1:1011408186:ios:3c928f0b7f2d4e1e7b8403',
    messagingSenderId: '1011408186',
    projectId: 'detection-app-23e70',
    storageBucket: 'detection-app-23e70.appspot.com',
    iosBundleId: 'com.example.detectionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBquyYHph6aBou3Iv5Mz5wbj13NtKZ-2ZU',
    appId: '1:1011408186:web:d778e8a7728118067b8403',
    messagingSenderId: '1011408186',
    projectId: 'detection-app-23e70',
    authDomain: 'detection-app-23e70.firebaseapp.com',
    storageBucket: 'detection-app-23e70.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoE7d7TwTCwZ_5_PoBvfgq_CmalQlwhvs',
    appId: '1:1011408186:android:e6a50119bf0e09c37b8403',
    messagingSenderId: '1011408186',
    projectId: 'detection-app-23e70',
    storageBucket: 'detection-app-23e70.appspot.com',
  );

}